name = "semiconductor-price-tracker"
compatibility_date = "2026-07-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Replace this placeholder with the ID of the same KV namespace used by the Cron Worker.
[[kv_namespaces]]
binding = "CRAWLER_DATA"
id = "be30f6be1f57408ca010b29750465603"
