export const seedItems = [
  {
    "id": 1,
    "group": "SOC芯片",
    "name": "NXP i.MX6DualLite",
    "spec": "i.MX6DualLite, Arm Cortex-A9, industrial temperature, MAPBGA, automotive/industrial embedded MPU",
    "supplier": "NXP",
    "mpn": "MCIMX6U5DVM10AC",
    "price": "72.44$",
    "unit": "USD",
    "source": "DigiKey",
    "url": "https://www.digikey.com/en/products?keywords=MCIMX6U5DVM10AC",
    "status": "已更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 2,
    "group": "SOC芯片",
    "name": "Imx9332",
    "spec": "i.MX 93 family, Arm Cortex-A55 + Cortex-M33, industrial temperature, BGA, edge/industrial MPU",
    "supplier": "NXP",
    "mpn": "MIMX9332CVVXMAC",
    "price": "22.72$",
    "unit": "USD",
    "source": "DigiKey",
    "url": "https://www.digikey.com/en/products?keywords=MIMX9332CVVXMAC",
    "status": "已更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 3,
    "group": "SOC芯片",
    "name": "Snapdragon S660",
    "spec": "Snapdragon 660 / SDM660, Kryo 260 octa-core mobile SoC, BGA, OEM/RFQ channel",
    "supplier": "Qualcomm",
    "mpn": "SDM660/QCS-9075-0-FCBGA1723+HS-TR-00-0-AC",
    "price": "533.74$",
    "unit": "USD",
    "source": "Octopart",
    "url": "https://octopart.com/search?q=SDM660%2FQCS-9075-0-FCBGA1723%2BHS-TR-00-0-AC",
    "status": "已更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 4,
    "group": "DDR内存",
    "name": "DDR5 16Gb (2Gx8) 4800/5600",
    "spec": "DDR5 16Gb (2Gx8), 4800/5600",
    "supplier": "Samsung / SK Hynix",
    "mpn": "—",
    "price": "48.5",
    "unit": "USD",
    "source": "TrendForce",
    "url": "https://www.trendforce.com/price/dram/dram_spot",
    "status": "已更新",
    "updated": "2026-07-14",
    "cadence": "每周"
  },
  {
    "id": 5,
    "group": "DDR内存",
    "name": "DDR5 16Gb (2Gx8) eTT",
    "spec": "DDR5 16Gb (2Gx8), eTT",
    "supplier": "Samsung",
    "mpn": "—",
    "price": "23.6",
    "unit": "USD",
    "source": "TrendForce",
    "url": "https://www.trendforce.com/price/dram/dram_spot",
    "status": "已更新",
    "updated": "2026-07-14",
    "cadence": "每周"
  },
  {
    "id": 55,
    "group": "DDR内存",
    "name": "DDR4 16Gb (2Gx8) 3200",
    "spec": "DDR4 16Gb (2Gx8), 3200",
    "supplier": "Samsung / SK Hynix / Micron",
    "mpn": "—",
    "price": "78.375",
    "unit": "USD",
    "source": "TrendForce",
    "url": "https://www.trendforce.com/price/dram/dram_spot",
    "status": "已更新",
    "updated": "2026-07-14",
    "cadence": "每周"
  },
  {
    "id": 56,
    "group": "DDR内存",
    "name": "DDR4 16Gb (2Gx8) eTT",
    "spec": "DDR4 16Gb (2Gx8), eTT",
    "supplier": "Spectek / Samsung / SK Hynix / Micron",
    "mpn": "—",
    "price": "11.5",
    "unit": "USD",
    "source": "TrendForce",
    "url": "https://www.trendforce.com/price/dram/dram_spot",
    "status": "已更新",
    "updated": "2026-07-14",
    "cadence": "每周"
  },
  {
    "id": 57,
    "group": "DDR内存",
    "name": "DDR4 8Gb (1Gx8) 3200",
    "spec": "DDR4 8Gb (1Gx8), 3200",
    "supplier": "Spectek / Samsung / SK Hynix",
    "mpn": "—",
    "price": "39.2",
    "unit": "USD",
    "source": "TrendForce",
    "url": "https://www.trendforce.com/price/dram/dram_spot",
    "status": "已更新",
    "updated": "2026-07-14",
    "cadence": "每周"
  },
  {
    "id": 58,
    "group": "DDR内存",
    "name": "DDR4 8Gb (1Gx8) eTT",
    "spec": "DDR4 8Gb (1Gx8), eTT",
    "supplier": "Samsung / SK Hynix / Micron / CXMT",
    "mpn": "—",
    "price": "4.214",
    "unit": "USD",
    "source": "TrendForce",
    "url": "https://www.trendforce.com/price/dram/dram_spot",
    "status": "已更新",
    "updated": "2026-07-14",
    "cadence": "每周"
  },
  {
    "id": 59,
    "group": "DDR内存",
    "name": "DDR3 4Gb 512Mx8 1600/1866",
    "spec": "DDR3 4Gb 512Mx8, 1600/1866",
    "supplier": "Nanya / SK Hynix / Samsung / Micron",
    "mpn": "—",
    "price": "13.05",
    "unit": "USD",
    "source": "TrendForce",
    "url": "https://www.trendforce.com/price/dram/dram_spot",
    "status": "已更新",
    "updated": "2026-07-14",
    "cadence": "每周"
  },
  {
    "id": 6,
    "group": "LCD屏幕",
    "name": "10.1 inch HD",
    "spec": "10.1 inch TFT LCD panel, 1280x800 WXGA, IPS, industrial grade, LVDS/eDP candidate",
    "supplier": "—",
    "mpn": "—",
    "price": "26.2",
    "unit": "USD",
    "source": "Panelook",
    "url": "https://www.panelook.com/sizmodlist.php?keyword=10.1+inch+HD+10.1+inch+TFT+LCD+panel%2C+1280x800+WXGA%2C+IPS%2C+industrial+grade%2C+LVDS%2FeDP+candidate+",
    "status": "已更新",
    "updated": "2026-07-08",
    "cadence": "每周"
  },
  {
    "id": 7,
    "group": "LCD屏幕",
    "name": "10.1 inch FHD",
    "spec": "10.1 inch TFT LCD panel, 1920x1200 WUXGA, IPS, LVDS/eDP candidate",
    "supplier": "AUO",
    "mpn": "G101UAN02.0",
    "price": "—",
    "unit": "—",
    "source": "Panelook",
    "url": "https://www.panelook.com/sizmodlist.php?keyword=G101UAN02.0",
    "status": "待更新",
    "updated": "2026-07-08",
    "cadence": "每周"
  },
  {
    "id": 8,
    "group": "塑料件",
    "name": "Handheld device housing",
    "spec": "PC+ABS UL94 V-0 injection-molded upper/lower handheld housing, textured black, custom tooling",
    "supplier": "Custom injection molding supplier",
    "mpn": "Custom RFQ - handheld device housing",
    "price": "9050 ton",
    "unit": "RMB",
    "source": "生意社 Sunsirs",
    "url": "https://www.sunsirs.com/uk/prodetail-713.html",
    "status": "已更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 9,
    "group": "塑料件",
    "name": "Diagnostic tool carrying case",
    "spec": "Hard plastic protective carrying case for VCI/diagnostic device, with foam insert option",
    "supplier": "Pelican / OEM case supplier",
    "mpn": "Pelican 1200-000-110",
    "price": "—",
    "unit": "RMB",
    "source": "Google 供应商检索",
    "url": "https://www.google.com/search?q=Pelican+1200-000-110",
    "status": "待更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 10,
    "group": "塑料件",
    "name": "Rubber protective boot",
    "spec": "TPE/TPU shock-protection rubber boot, overmold or separate sleeve, custom tooling",
    "supplier": "Custom rubber molding supplier",
    "mpn": "Custom RFQ - TPU protective boot",
    "price": "定制",
    "unit": "—",
    "source": "UL Prospector",
    "url": "https://www.ulprospector.com/plastics",
    "status": "已更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 11,
    "group": "塑料件",
    "name": "Battery cover",
    "spec": "PC+ABS injection-molded battery door/cover, latch structure, custom tooling",
    "supplier": "Custom injection molding supplier",
    "mpn": "Custom RFQ - battery cover",
    "price": "12566.67 ton",
    "unit": "RMB",
    "source": "生意社 Sunsirs",
    "url": "https://www.sunsirs.com/uk/prodetail-172.html",
    "status": "已更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 12,
    "group": "塑料件",
    "name": "Front bezel",
    "spec": "PC+ABS or ABS LCD front bezel, coating/texture/silk-screen option, custom tooling",
    "supplier": "Custom injection molding supplier",
    "mpn": "Custom RFQ - LCD front bezel",
    "price": "—",
    "unit": "RMB",
    "source": "UL Prospector",
    "url": "https://www.ulprospector.com/plastics",
    "status": "待更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 13,
    "group": "塑料件",
    "name": "Button/keypad assembly",
    "spec": "Silicone rubber keypad with conductive carbon pills plus plastic keycap assembly",
    "supplier": "Custom keypad supplier",
    "mpn": "Custom RFQ - silicone keypad assembly",
    "price": "—",
    "unit": "RMB",
    "source": "UL Prospector",
    "url": "https://www.ulprospector.com/plastics",
    "status": "待更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 14,
    "group": "塑料件",
    "name": "Connector dust cap",
    "spec": "Plastic/rubber connector dust cap, tethered protective cap, IP-rated option",
    "supplier": "Custom rubber/plastic supplier",
    "mpn": "Custom RFQ - connector dust cap",
    "price": "—",
    "unit": "—",
    "source": "UL Prospector",
    "url": "https://www.ulprospector.com/plastics",
    "status": "待更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 15,
    "group": "塑料件",
    "name": "DIN-rail / mounting bracket",
    "spec": "DIN-rail / wall mounting bracket, PA66/PC+ABS, industrial enclosure accessory",
    "supplier": "Phoenix Contact / OEM supplier",
    "mpn": "UM108-DINRAIL",
    "price": "—",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.com/en/products?keywords=UM108-DINRAIL",
    "status": "待更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 16,
    "group": "电池",
    "name": "18650 2600mAh",
    "spec": "18650 cylindrical Li-ion cell, 3.6V/3.7V, 2600mAh class, industrial pack candidate",
    "supplier": "Microchip Technology",
    "mpn": "MCP73832T-2ACI/MC",
    "price": "—",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.sg/zh/products/filter/%E7%94%B5%E6%B1%A0%E5%85%85%E7%94%B5%E5%99%A8/781?s=N4IgTCBcDaIDIEsC0CD2A7ABAYQKYBt8QBdAXyA",
    "status": "待更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 17,
    "group": "电池",
    "name": "CR2032 coin cell",
    "spec": "CR2032 lithium coin cell, 3V, 20mm diameter, 3.2mm height",
    "supplier": "Panasonic",
    "mpn": "CR2032",
    "price": "1.6$",
    "unit": "USD",
    "source": "DigiKey",
    "url": "https://www.digikey.sg/zh/products/detail/gp-batteries-americas-inc/CR2032/24819158",
    "status": "已更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 18,
    "group": "SGT MOS / MOSFET",
    "name": "Infineon IPB017N10N5",
    "spec": "100V OptiMOS N-channel power MOSFET, low RDS(on), D2PAK/TO package family",
    "supplier": "Infineon",
    "mpn": "IPB017N10N5ATMA1",
    "price": "$6.67",
    "unit": "USD",
    "source": "DigiKey",
    "url": "https://www.digikey.com/en/products/detail/infineon-technologies/IPB017N10N5ATMA1/5213937",
    "status": "已更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 19,
    "group": "SGT MOS / MOSFET",
    "name": "onsemi NTMFS5C646NL",
    "spec": "N-channel power MOSFET, shielded gate/trench technology, Power56 package candidate",
    "supplier": "onsemi",
    "mpn": "NTMFS5C646NLT1G",
    "price": "—",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.com/en/products?keywords=NTMFS5C646NLT1G",
    "status": "待更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 20,
    "group": "SGT MOS / MOSFET",
    "name": "Vishay SQJQ480E",
    "spec": "Automotive-grade N-channel MOSFET, PowerPAK package, AEC-Q101 candidate",
    "supplier": "Vishay",
    "mpn": "SQJQ480E-T1_GE3",
    "price": "—",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.com/en/products?keywords=SQJQ480E-T1_GE3",
    "status": "待更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 21,
    "group": "SGT MOS / MOSFET",
    "name": "ST STL110N10F7",
    "spec": "100V STripFET F7 N-channel power MOSFET, PowerFLAT package family",
    "supplier": "STMicroelectronics",
    "mpn": "STL110N10F7",
    "price": "—",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.com/en/products?keywords=STL110N10F7",
    "status": "待更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 22,
    "group": "SGT MOS / MOSFET",
    "name": "TI CSD19536KTT",
    "spec": "100V NexFET N-channel power MOSFET, TO-263/KTT package",
    "supplier": "Texas Instruments",
    "mpn": "CSD19536KTTT",
    "price": "—",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.com/en/products?keywords=CSD19536KTTT",
    "status": "待更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 23,
    "group": "SGT MOS / MOSFET",
    "name": "Nexperia PSMN2R0-40YLD",
    "spec": "40V LFPAK automotive N-channel MOSFET, low RDS(on)",
    "supplier": "Nexperia",
    "mpn": "PSMN2R0-40YLDX",
    "price": "—",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.com/en/products?keywords=PSMN2R0-40YLDX",
    "status": "待更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 24,
    "group": "SGT MOS / MOSFET",
    "name": "AO3400A",
    "spec": "30V SOT-23 logic-level N-channel MOSFET, small signal/load switching",
    "supplier": "Alpha & Omega",
    "mpn": "AO3400A",
    "price": "SGD 0.72",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.sg/en/products/detail/alpha-omega-semiconductor-inc/AO3400A/1855772",
    "status": "已更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 25,
    "group": "SGT MOS / MOSFET",
    "name": "Infineon BTS50015-1TAD",
    "spec": "PROFET smart high-side power switch, automotive/industrial load switching",
    "supplier": "Infineon",
    "mpn": "BTS50015-1TAD",
    "price": "—",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.com/en/products?keywords=BTS50015-1TAD",
    "status": "待更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 26,
    "group": "SGT MOS / MOSFET",
    "name": "TI TPS22965",
    "spec": "Low RON load switch IC, controlled slew rate, small package",
    "supplier": "Texas Instruments",
    "mpn": "TPS22965DSGR",
    "price": "—",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.com/en/products/detail/texas-instruments/TPS22965DSGR/3789575",
    "status": "待更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 27,
    "group": "SGT MOS / MOSFET",
    "name": "onsemi FPF2123",
    "spec": "Current-limited load switch with controlled turn-on, compact package",
    "supplier": "onsemi",
    "mpn": "FPF2123",
    "price": "—",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.com/en/products?keywords=FPF2123",
    "status": "待更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 28,
    "group": "SGT MOS / MOSFET",
    "name": "SMBJ24CA",
    "spec": "SMBJ series bidirectional TVS diode, 24V standoff, DO-214AA/SMB",
    "supplier": "Littelfuse / Vishay",
    "mpn": "SMBJ24CA",
    "price": "—",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.com/en/products?keywords=SMBJ24CA",
    "status": "待更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 29,
    "group": "SGT MOS / MOSFET",
    "name": "Half-bridge MOSFET module",
    "spec": "Integrated half-bridge / smart power stage for motor or load control",
    "supplier": "Infineon",
    "mpn": "BTN8982TA",
    "price": "—",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.com/en/products?keywords=BTN8982TA",
    "status": "待更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 30,
    "group": "PCB",
    "name": "8029",
    "spec": "通用万能版",
    "supplier": "Vector Electronics",
    "mpn": "8029",
    "price": "6.41$",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.sg/zh/products/filter/%E6%9C%89%E5%AD%94%E5%8E%9F%E5%9E%8B%E6%9D%BF/636?s=N4IgTCBcDaIGoFMDGAXA9gJwAQFEA2yKGaAdgJZIDOIAugL5A",
    "status": "已更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 31,
    "group": "PCB",
    "name": "7100-45",
    "spec": "通用万能版",
    "supplier": "Twin Industries",
    "mpn": "7100-45",
    "price": "4.5$",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.sg/zh/products/filter/%E6%9C%89%E5%AD%94%E5%8E%9F%E5%9E%8B%E6%9D%BF/636?s=N4IgTCBcDaICoHcCWA7ABASRQEwK4GcAXAJyQFN8QBdAXyA",
    "status": "已更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 32,
    "group": "PCB",
    "name": "Stripboard, 2.54mm",
    "spec": "2.54mm stripboard / breadboard-style prototyping PCB, FR-4",
    "supplier": "BusBoard Prototype Systems",
    "mpn": "SB300",
    "price": "—",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.com/en/products?keywords=SB300",
    "status": "待更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 33,
    "group": "PCB",
    "name": "RE318, 欧卡尺寸",
    "spec": "Eurocard prototype board, 100x160mm class, FR-4, through-hole grid",
    "supplier": "Roth Elektronik",
    "mpn": "RE318-LF",
    "price": "—",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.com/en/products?keywords=RE318-LF",
    "status": "待更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 34,
    "group": "PCB",
    "name": "202-0011-01",
    "spec": "SMT转DIP",
    "supplier": "SchmartBoard",
    "mpn": "202-0011-01",
    "price": "10$",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.sg/zh/products/filter/%E6%9C%89%E5%AD%94%E5%8E%9F%E5%9E%8B%E6%9D%BF/636?s=N4IgTCBcDaICoHcCWA7ABASRQEwK4GcAXAJyQFN8QBdAXyA",
    "status": "已更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 35,
    "group": "PCB",
    "name": "8000-45",
    "spec": "SMT转DIP",
    "supplier": "SchmartBoard",
    "mpn": "8000-45",
    "price": "9.9$",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.sg/zh/products/filter/%E6%9C%89%E5%AD%94%E5%8E%9F%E5%9E%8B%E6%9D%BF/636?s=N4IgTCBcDaICoHcCWA7ABASRQEwK4GcAXAJyQFN9QBdAXyA",
    "status": "已更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 36,
    "group": "PCB",
    "name": "SOT23-8 to DIP",
    "spec": "SOT-23 / SOT-23-8 to DIP breakout adapter board",
    "supplier": "Adafruit",
    "mpn": "1230",
    "price": "—",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.com/en/products?keywords=1230",
    "status": "待更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 37,
    "group": "PCB",
    "name": "0.5mm Pitch 60-pin to DIP",
    "spec": "0.5mm pitch 60-pin FFC/FPC/QFP breakout to DIP adapter",
    "supplier": "Proto-Advantage",
    "mpn": "PA0109",
    "price": "—",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.com/en/products?keywords=PA0109",
    "status": "待更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 38,
    "group": "MCU芯片",
    "name": "STM32F103C8T6",
    "spec": "ARM Cortex-M3 32-bit MCU, 64KB Flash, 20KB SRAM, LQFP-48",
    "supplier": "STMicroelectronics",
    "mpn": "STM32F103C8T6",
    "price": "$7.03",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.com/en/products/detail/stmicroelectronics/STM32F103C8T6/1646338",
    "status": "已更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 39,
    "group": "MCU芯片",
    "name": "STM32F407VGT6",
    "spec": "ARM Cortex-M4 32-bit MCU, 1MB Flash, 192KB SRAM, LQFP-100",
    "supplier": "STMicroelectronics",
    "mpn": "STM32F407VGT6",
    "price": "$13.24",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.com/en/products/detail/stmicroelectronics/STM32F407VGT6/2747117",
    "status": "已更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 40,
    "group": "MCU芯片",
    "name": "S32K148UJT0VLLT",
    "spec": "Automotive MCU",
    "supplier": "NXP",
    "mpn": "S32K148UJT0VLLT",
    "price": "12.9$",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.sg/zh/products/detail/nxp-usa-inc/FS32K148UJT0VLLT/10816049?s=N4IgTCBcDaIMoGYwGkCMAWAHAVQFIBUAGANQBlT8QBdAXyA",
    "status": "已更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 41,
    "group": "MCU芯片",
    "name": "S32K312NHT0MPBST",
    "spec": "Automotive MCU",
    "supplier": "NXP",
    "mpn": "S32K312NHT0MPBST",
    "price": "6.56$",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.sg/zh/products/detail/nxp-usa-inc/S32K312NHT0MPBST/16674955?s=N4IgTCBcDaIMoGYwGkEEYwDkASAVADALIAKAQnLiALoC%2BQA",
    "status": "已更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 42,
    "group": "MCU芯片",
    "name": "NXP MPC5744P",
    "spec": "Power Architecture automotive MCU, MPC5744P family, powertrain/motor control",
    "supplier": "NXP",
    "mpn": "MPC5744PMLQ9",
    "price": "—",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.com/en/products?keywords=MPC5744PMLQ9",
    "status": "待更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 43,
    "group": "MCU芯片",
    "name": "Infineon TC275",
    "spec": "AURIX TC27x TriCore automotive MCU, 200MHz class, safety/security features",
    "supplier": "Infineon",
    "mpn": "SAK-TC275TP-64F200N DC",
    "price": "—",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.com/en/products?keywords=SAK-TC275TP-64F200N+DC",
    "status": "待更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 44,
    "group": "MCU芯片",
    "name": "Infineon TC377",
    "spec": "AURIX TC37x TriCore automotive MCU, TC3xx family, high performance safety MCU",
    "supplier": "Infineon",
    "mpn": "SAK-TC377TP-96F300S AE",
    "price": "—",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.com/en/products?keywords=SAK-TC377TP-96F300S+AE",
    "status": "待更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 45,
    "group": "MCU芯片",
    "name": "Infineon TC397",
    "spec": "AURIX TC39x TriCore high-end automotive MCU, TC3xx family",
    "supplier": "Infineon",
    "mpn": "SAK-TC397XP-256F300S BC",
    "price": "—",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.com/en/products?keywords=SAK-TC397XP-256F300S+BC",
    "status": "待更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 46,
    "group": "MCU芯片",
    "name": "Renesas RH850/F1K",
    "spec": "RH850/F1K automotive MCU, body/chassis control, 144-pin class candidate",
    "supplier": "Renesas",
    "mpn": "R7F7015873AFP-C",
    "price": "—",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.com/en/products?keywords=R7F7015873AFP-C",
    "status": "待更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 47,
    "group": "MCU芯片",
    "name": "Renesas RH850/P1x",
    "spec": "RH850/P1x automotive MCU, powertrain/safety control family",
    "supplier": "Renesas",
    "mpn": "R7F701373EAFP-C",
    "price": "—",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.com/en/products?keywords=R7F701373EAFP-C",
    "status": "待更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 48,
    "group": "MCU芯片",
    "name": "Renesas RA6M5",
    "spec": "RA6M5 industrial MCU, Arm Cortex-M33, TrustZone, 200MHz class",
    "supplier": "Renesas",
    "mpn": "R7FA6M5BH3CFB",
    "price": "—",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.com/en/products?keywords=R7FA6M5BH3CFB",
    "status": "待更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 49,
    "group": "MCU芯片",
    "name": "Microchip ATSAME70Q21",
    "spec": "ARM Cortex-M7 industrial MCU, 300MHz class, 2MB Flash, LQFP/BGA candidate",
    "supplier": "Microchip",
    "mpn": "ATSAME70Q21B-AN",
    "price": "—",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.com/en/products?keywords=ATSAME70Q21B-AN",
    "status": "待更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 50,
    "group": "MCU芯片",
    "name": "Microchip PIC32MZ2048EFH",
    "spec": "32-bit MIPS MCU, 2MB Flash, high-performance PIC32MZ EF family",
    "supplier": "Microchip",
    "mpn": "PIC32MZ2048EFH144-I/PH",
    "price": "—",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.com/en/products?keywords=PIC32MZ2048EFH144-I%2FPH",
    "status": "待更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 51,
    "group": "MCU芯片",
    "name": "TI TM4C1294NCPDT",
    "spec": "ARM Cortex-M4F Ethernet MCU, 1MB Flash, 120MHz class, Tiva C series",
    "supplier": "Texas Instruments",
    "mpn": "TM4C1294NCPDT",
    "price": "—",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.com/en/products?keywords=TM4C1294NCPDT",
    "status": "待更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 52,
    "group": "MCU芯片",
    "name": "TI TMS320F28379D",
    "spec": "C2000 dual-core real-time control MCU, 200MHz class, motor/power control",
    "supplier": "Texas Instruments",
    "mpn": "TMS320F28379DPTPT",
    "price": "—",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.com/en/products?keywords=TMS320F28379DPTPT",
    "status": "待更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 53,
    "group": "MCU芯片",
    "name": "MSP430FR5994",
    "spec": "Ultra-low-power FRAM MCU, MSP430FR5994 family, 256KB FRAM class",
    "supplier": "Texas Instruments",
    "mpn": "MSP430FR5994IPM",
    "price": "—",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.com/en/products?keywords=MSP430FR5994IPM",
    "status": "待更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  },
  {
    "id": 54,
    "group": "MCU芯片",
    "name": "ESP32-WROOM-32E",
    "spec": "ESP32 Wi-Fi/Bluetooth module, ESP32-D0WD-V3, 4MB Flash, non-safety connectivity",
    "supplier": "Espressif",
    "mpn": "ESP32-WROOM-32E-N4",
    "price": "$4.99",
    "unit": "—",
    "source": "DigiKey",
    "url": "https://www.digikey.com/en/products/detail/espressif-systems/ESP32-WROOM-32E-N4/11613125",
    "status": "已更新",
    "updated": "2026-07-08",
    "cadence": "每月"
  }
] as const;

// 后两张表中的覆盖数据：这些大品类不再沿用总表里的产品级小项。
export const referenceSheetItems = [
  { id: 60, group: "LCD屏幕", name: "LCD TV", spec: "LCD TV panel", supplier: "—", mpn: "—", price: "126", unit: "USD", source: "TrendForce", url: "https://www.trendforce.com/", status: "已更新", updated: "2026-06-22", cadence: "每周" },
  { id: 61, group: "LCD屏幕", name: "Monitor", spec: "Monitor panel", supplier: "—", mpn: "—", price: "63.6", unit: "USD", source: "TrendForce", url: "https://www.trendforce.com/", status: "已更新", updated: "2026-06-22", cadence: "每周" },
  { id: 62, group: "LCD屏幕", name: "Notebook", spec: "Notebook panel", supplier: "—", mpn: "—", price: "26.7", unit: "USD", source: "TrendForce", url: "https://www.trendforce.com/", status: "已更新", updated: "2026-06-22", cadence: "每周" },

  { id: 63, group: "电池", name: "方形三元电芯（EV）", spec: "Square Ternary Battery Cell for EV", supplier: "—", mpn: "—", price: "0.60", unit: "RMB/Wh", source: "TrendForce", url: "https://www.trendforce.com/", status: "已更新", updated: "2026-07-06", cadence: "每周" },
  { id: 64, group: "电池", name: "方形磷酸铁锂电芯（EV）", spec: "Square LFP Battery Cell for EV", supplier: "—", mpn: "—", price: "0.39", unit: "RMB/Wh", source: "TrendForce", url: "https://www.trendforce.com/", status: "已更新", updated: "2026-07-06", cadence: "每周" },
  { id: 65, group: "电池", name: "软包三元电芯（EV）", spec: "Pouch Ternary Battery Cell for EV", supplier: "—", mpn: "—", price: "0.61", unit: "RMB/Wh", source: "TrendForce", url: "https://www.trendforce.com/", status: "已更新", updated: "2026-07-06", cadence: "每周" },
  { id: 66, group: "电池", name: "方形磷酸铁锂电芯（储能）", spec: "Square LFP Battery Cell for Energy Storage", supplier: "—", mpn: "—", price: "0.37", unit: "RMB/Wh", source: "TrendForce", url: "https://www.trendforce.com/", status: "已更新", updated: "2026-07-06", cadence: "每周" },
  { id: 67, group: "电池", name: "钴酸锂电芯（消费类）", spec: "Lithium Cobaltate Battery Cell for Consumer", supplier: "—", mpn: "—", price: "8.40", unit: "RMB/Ah", source: "TrendForce", url: "https://www.trendforce.com/", status: "已更新", updated: "2026-07-06", cadence: "每周" },
  { id: 68, group: "电池", name: "方形三元电池包", spec: "Square Ternary Battery Pack", supplier: "—", mpn: "—", price: "0.76", unit: "RMB/Wh", source: "TrendForce", url: "https://www.trendforce.com/", status: "已更新", updated: "2026-07-06", cadence: "每周" },
  { id: 69, group: "电池", name: "方形磷酸铁锂电池包", spec: "Square LFP Battery Pack", supplier: "—", mpn: "—", price: "0.51", unit: "RMB/Wh", source: "TrendForce", url: "https://www.trendforce.com/", status: "已更新", updated: "2026-07-06", cadence: "每周" },

  { id: 70, group: "塑料件", name: "ABS", spec: "ABS 原材料价格", supplier: "—", mpn: "—", price: "9916.67", unit: "RMB/吨", source: "生意社 Sunsirs", url: "https://www.sunsirs.com/uk/prodetail-713.html", status: "已更新", updated: "2026-07-15", cadence: "每日" },
  { id: 71, group: "塑料件", name: "PVC", spec: "PVC 原材料价格", supplier: "—", mpn: "—", price: "4475", unit: "RMB/吨", source: "生意社 Sunsirs", url: "https://www.sunsirs.com/uk/prodetail-107.html", status: "已更新", updated: "2026-07-15", cadence: "每日" },
  { id: 72, group: "塑料件", name: "PC", spec: "PC 原材料价格", supplier: "—", mpn: "—", price: "13033.33", unit: "RMB/吨", source: "生意社 Sunsirs", url: "https://www.sunsirs.com/uk/prodetail-172.html", status: "已更新", updated: "2026-07-15", cadence: "每日" },
  { id: 73, group: "塑料件", name: "PET", spec: "PET 原材料价格", supplier: "—", mpn: "—", price: "7285", unit: "RMB/吨", source: "生意社 Sunsirs", url: "https://www.sunsirs.com/uk/prodetail-173.html", status: "已更新", updated: "2026-07-14", cadence: "每日" },
  { id: 74, group: "塑料件", name: "PP", spec: "PP 原材料价格", supplier: "—", mpn: "—", price: "9093.33", unit: "RMB/吨", source: "生意社 Sunsirs", url: "https://www.sunsirs.com/uk/prodetail-718.html", status: "已更新", updated: "2026-07-15", cadence: "每日" },
] as const;

export const categorySources = [
  {
    "group": "DDR内存",
    "label": "DRAM 现货价格",
    "source": "TrendForce",
    "url": "https://www.trendforce.com/price/dram/dram_spot",
    "note": "对应 DDR-BATTERY-LCD 表"
  },
  {
    "group": "LCD屏幕",
    "label": "LCD 面板价格",
    "source": "TrendForce",
    "url": "https://www.trendforce.com/",
    "note": "对应 DDR-BATTERY-LCD 表"
  },
  {
    "group": "电池",
    "label": "电池与原材料价格",
    "source": "TrendForce",
    "url": "https://www.trendforce.com/",
    "note": "对应 DDR-BATTERY-LCD 表"
  },
  {
    "group": "塑料件",
    "label": "ABS",
    "source": "生意社 Sunsirs",
    "url": "https://www.sunsirs.com/uk/prodetail-713.html",
    "note": "对应塑料件表"
  },
  {
    "group": "塑料件",
    "label": "PVC",
    "source": "生意社 Sunsirs",
    "url": "https://www.sunsirs.com/uk/prodetail-107.html",
    "note": "对应塑料件表"
  },
  {
    "group": "塑料件",
    "label": "PC",
    "source": "生意社 Sunsirs",
    "url": "https://www.sunsirs.com/uk/prodetail-172.html",
    "note": "对应塑料件表"
  },
  {
    "group": "塑料件",
    "label": "PET",
    "source": "生意社 Sunsirs",
    "url": "https://www.sunsirs.com/uk/prodetail-173.html",
    "note": "对应塑料件表"
  },
  {
    "group": "塑料件",
    "label": "PP",
    "source": "生意社 Sunsirs",
    "url": "https://www.sunsirs.com/uk/prodetail-718.html",
    "note": "对应塑料件表"
  }
] as const;
